### ISSUE TITLE
Dolphin emulator

### ISSUE THREAD

**Issue by microrache** [spleen1981/retroarch-kodi-addon-CoreELEC#2]
Not neccessarily an issue to this great addon, but I am desperately looking for a S922X-build of the dolphin-core running with Retroarch. Is there a chance anyone already got Dolphin running with this version of Retroarch on an Odroid N2+?

**Comment by spleen1981** [comment]
CoreELEC userspace is 32bit (armhf), hence regular retroarch addon is 32bit as well: Dolphin core is only available for 64bit systems (aarch64), so it can't be included in a armhf build of the addon.

As explained in [Experimental build options](https://github.com/spleen1981/retroarch-kodi-addon-CoreELEC#experimental-build-options), you can build an "hacked" version of the addon which allows to run an aarch64 version of the addon in the armhf userspace of CoreELEC. In this case all aarch64 cores will be available, including Dolphin.
It's experimental and "dirty" hack, hence built addon is not distributed and bugs are reasonably expected, but you are free to try, it should work.

Otherwise you need to build a regular aarch64 version of the plugin and install in a aarch64 distro other than CoreELEC.

Anyways don't expect decent performances with Dolphin on this hardware.

**Comment by spleen1981** [comment]
However not an issue with the addon, as you said.
