### ISSUE TITLE
A novice question

### ISSUE THREAD

**Issue by yuanxiang2015** [spleen1981/retroarch-kodi-addon-CoreELEC#7]
I can't use the CEC Mini function, so I can't control the main menu of retroarch, neither the handle nor the touch screen. I don't know how to solve it.
This paragraph is written with translation tools, because I don't understand English.

**Comment by spleen1981** [comment]
Most convenient way for first setup of the system is a keyboard, a [gamepad preconfigured in retroarch](https://docs.libretro.com/guides/controller-autoconfiguration/) (e.g. xbox360) or a remote controller if your systems have CEC.
Of course retroarch.cfg can also be modified by hand through SSH (when retroarch is closed, otherwise changes will be overwritten on exit)…
If you have a gamepad not covered by retroarch defaults, once configured during first setup you can use to navigate.

- Which system/OS are you using which has a touchscreen? 
- How are you navigating kodi? 
- Assuming handle means gamepad, which one? Wired? Bluetooth?

**Comment by yuanxiang2015** [comment]
This problem is solved. I changed a setting in the (retroarch. CFG) file.Specifies the drive of the handle.
The problem now is that I can't find the available core file.

**Comment by yuanxiang2015** [comment]
Sorry, I found the core position. Sorry.
